name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sync images
        run: |
          rm -rf docs/img
          mkdir -p docs/img
          cp -r src/img/* docs/img/